@echo off
title Password Manager - Clean Build Artifacts
echo.
echo ============================================
echo   Clean build artifacts, source and data safe
echo ============================================
echo.

rem ---- 1. delete target, regenerated by cargo build ----
if exist "%~dp0target" (
    echo [1/2] Deleting target...
    rmdir /s /q "%~dp0target"
    if errorlevel 1 (
        echo [FAILED] target may be locked by a running program
        echo Close pswd.exe and run this script again.
    ) else (
        echo [OK] Deleted about 1.2 GB
    )
) else (
    echo [1/2] target not found, skip
)

rem ---- 2. delete exe copies in new_test ----
set "REMOVED="
if exist "%~dp0new_test\pswd.exe" (
    del /q "%~dp0new_test\pswd.exe"
    set "REMOVED=1"
)
if exist "%~dp0new_test\migrate_legacy.exe" (
    del /q "%~dp0new_test\migrate_legacy.exe"
    set "REMOVED=1"
)
if defined REMOVED (
    echo [2/2] exe copies in new_test deleted
    rmdir "%~dp0new_test" 2>nul
) else (
    echo [2/2] no exe copies in new_test, skip
)

echo.
echo Done. NOT touched:
echo   - src source, Cargo.toml, README and so on
echo   - pswd.db, your password database
echo.
echo To rebuild: cargo build --release
echo.
pause
